def image

pipeline {
    agent any

    environment {
        DOCKER_USERNAME = 'kkkqwerasdf123'
        DOCKER_REPOSITORY = 'neohoon'
        DOCKER_TAG_PREFIX = "drumtong-front-"
        DOCKER_IMAGE = "$DOCKER_USERNAME/$DOCKER_REPOSITORY"
    }

    tools {
        dockerTool 'docker'
    }

    stages {
        stage('checkout') {
            steps {
                git(url: 'https://github.com/kkkqwerasdf123/neohoon', branch: 'develop', changelog: true)
            }
        }
        stage('build docker image') {
            steps {
                dir('front') {
                    script {
                        image = docker.build(env.DOCKER_IMAGE)
                    }
                }
            }
        }
        stage('push docker image') {
            steps {
                dir('front') {
                    script {
                        image = docker.build(env.DOCKER_IMAGE)
                        docker.withRegistry('https://registry.hub.docker.com', 'hub.docker.kkkqwerasdf123') {
//                             image.push(env.DOCKER_TAG_PREFIX + '-' + env.BUILD_NUMBER)
                            image.push(env.DOCKER_TAG_PREFIX)
                        }
                    }
                }

            }
        }
//     stage('login docker') {
//         steps {
//             sh 'echo -n $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --passwrod-stdin '
//         }
//     }
//     stage('push docker image') {
//         steps {
//             sh 'docker push $DOCKER_IMAGE'
//             sh 'docker push $DOCKER_IMAGE_LATEST'
//         }
//     }
//     stage('remove docker image') {
//         steps {
//             sh 'docker rmi $DOCKER_IMAGE'
//             sh 'docker rmi $DOCKER_IMAGE_LATEST'
//         }
//     }
    }
}