pipeline {
    agent any

    environment {
        DOCKER_USERNAME = 'kkkqwerasdf123'
        DOCKER_REPOSITORY = 'neohoon'
        DOCKER_TAG_PREFIX = "drumtong-front"
        DOCKER_IMAGE = "$DOCKER_USERNAME/$DOCKER_REPOSITORY"
        DOCKER_IMAGE_CURRENT = "$DOCKER_IMAGE:$DOCKER_TAG_PREFIX-$BUILD_NUMBER"
        DOCKER_IMAGE_LATEST = "$DOCKER_IMAGE:$DOCKER_TAG_PREFIX"
    }

    tools {
        dockerTool 'docker1'
    }

    stages {
        stage('checkout') {
            steps {
                git(url: 'https://github.com/kkkqwerasdf123/neohoon', branch: 'develop', changelog: true)
            }
        }
        stage('build docker image') {
            steps {
                dir('front') {
                    sh 'docker build . -t $DOCKER_IMAGE'
                    sh 'docker tag $DOCKER_IMAGE $DOCKER_IMAGE_CURRENT'
                    sh 'docker tag $DOCKER_IMAGE $DOCKER_IMAGE_LATEST'
                }
            }
        }
        stage('login docker repository') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'hub.docker.kkkqwerasdf123', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASSWORD')]) {
                    sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }
        stage('push docker image') {
            steps {
                script {
                    sh 'docker push $DOCKER_IMAGE_CURRENT'
                    sh 'docker push $DOCKER_IMAGE_LATEST'
                }
            }
        }
        stage('cleanup docker local image') {
            steps {
                script {
                    sh 'docker rmi $DOCKER_IMAGE_CURRENT'
                    sh 'docker rmi $DOCKER_IMAGE_LATEST'
                }
            }
        }
    }
}